services:
  # Database container
  postgres:
    image: postgres:16-alpine
    container_name: vidyalayaone-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - vidyalayaone-network

  # Migration container
  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    container_name: vidyalayaone-migration
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AUTH_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_db
      - SCHOOL_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/school_db
      - PROFILE_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/profile_db
      - ATTENDANCE_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/attendance_db
      - PAYMENT_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payment_db
    networks:
      - vidyalayaone-network
    restart: "no"

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: vidyalayaone-auth
    ports:
      - "3001:3001"
      - "5556:5556"  # Add this line for Prisma Studio
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_db
      - PORT=3001
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:8080,http://localhost:8081
      - JWT_ACCESS_SECRET=your_access_secret_here
    volumes:
    - ./apps/auth-service:/app/apps/auth-service
    - ./packages:/app/packages
    - /app/node_modules
    - /app/apps/auth-service/node_modules
    # Exclude generated Prisma client from volume mount
    - /app/apps/auth-service/src/generated
    - /app/apps/auth-service/node_modules/.prisma
    # Exclude built package dist folders
    - /app/packages/common-middleware/dist
    - /app/packages/common-utils/dist
    - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

  # School Service
  school-service:
    build:
      context: .
      dockerfile: apps/school-service/Dockerfile
    container_name: vidyalayaone-school
    ports:
      - "3002:3002"
      - "5557:5557"
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/school_db
      - PORT=3002
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:8080,http://localhost:8081
    volumes:
    - ./apps/school-service:/app/apps/school-service
    - ./packages:/app/packages
    - /app/node_modules
    - /app/apps/school-service/node_modules
    # Exclude generated Prisma client from volume mount
    - /app/apps/school-service/src/generated
    - /app/apps/school-service/node_modules/.prisma
    # Exclude built package dist folders
    - /app/packages/common-middleware/dist
    - /app/packages/common-utils/dist
    - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

  # Profile Service
  profile-service:
    build:
      context: .
      dockerfile: apps/profile-service/Dockerfile
    container_name: vidyalayaone-profile
    ports:
      - "3003:3003"
      - "5558:5558"
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/profile_db
      - PORT=3003
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:8080,http://localhost:8081
    volumes:
    - ./apps/profile-service:/app/apps/profile-service
    - ./packages:/app/packages
    - /app/node_modules
    - /app/apps/profile-service/node_modules
    # Exclude generated Prisma client from volume mount
    - /app/apps/profile-service/src/generated
    - /app/apps/profile-service/node_modules/.prisma
    # Exclude built package dist folders
    - /app/packages/common-middleware/dist
    - /app/packages/common-utils/dist
    - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

  # Payment Service
  payment-service:
    build:
      context: .
      dockerfile: apps/payment-service/Dockerfile
    container_name: vidyalayaone-payment
    ports:
      - "3005:3005"
      - "5561:5561"
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payment_db
      - PORT=3005
      - NODE_ENV=development
      - RAZORPAY_KEY_ID=your_razorpay_key_id_here
      - RAZORPAY_KEY_SECRET=your_razorpay_key_secret_here
      - RAZORPAY_WEBHOOK_SECRET=your_webhook_secret_here
      - SCHOOL_SERVICE_URL=http://school-service:3002
      - CORS_ORIGIN=http://localhost:8080,http://localhost:8081
    volumes:
    - ./apps/payment-service:/app/apps/payment-service
    - ./packages:/app/packages
    - /app/node_modules
    - /app/apps/payment-service/node_modules
    # Exclude generated Prisma client from volume mount
    - /app/apps/payment-service/src/generated
    - /app/apps/payment-service/node_modules/.prisma
    # Exclude built package dist folders
    - /app/packages/common-middleware/dist
    - /app/packages/common-utils/dist
    - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

  # Attendance Service
  attendance-service:
    build:
      context: .
      dockerfile: apps/attendance-service/Dockerfile
    container_name: vidyalayaone-attendance
    ports:
      - "3004:3004"
      - "5560:5560"
    depends_on:
      migration:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/attendance_db
      - PORT=3004
      - NODE_ENV=development
    volumes:
    - ./apps/attendance-service:/app/apps/attendance-service
    - ./packages:/app/packages
    - /app/node_modules
    - /app/apps/attendance-service/node_modules
    # Exclude generated Prisma client from volume mount
    - /app/apps/attendance-service/src/generated
    - /app/apps/attendance-service/node_modules/.prisma
    # Exclude built package dist folders
    - /app/packages/common-middleware/dist
    - /app/packages/common-utils/dist
    - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: vidyalayaone-gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - school-service
      - profile-service
      - payment-service
      - attendance-service
    environment:
      - PORT=3000
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3001
      - SCHOOL_SERVICE_URL=http://school-service:3002
      - PAYMENT_SERVICE_URL=http://payment-service:3005
      - ATTENDANCE_SERVICE_URL=http://attendance-service:3004
      - PROFILE_SERVICE_URL=http://profile-service:3003
      - CORS_ORIGIN=http://localhost:8080,http://localhost:8081
      - JWT_ACCESS_SECRET=your_access_secret_here
    volumes:
      - ./apps/api-gateway:/app/apps/api-gateway
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/api-gateway/node_modules
      # Exclude built package dist folders
      - /app/packages/common-middleware/dist
      - /app/packages/common-utils/dist
      - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

  # School Frontend
  school-frontend:
    build:
      context: .
      dockerfile: apps/school-frontend/Dockerfile
    container_name: vidyalayaone-frontend
    ports:
      - "8080:8080"
    depends_on:
      - api-gateway
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_AUTH_SERVICE_URL=http://localhost:3001
      - VITE_SCHOOL_SERVICE_URL=http://localhost:3002
      - VITE_PROFILE_SERVICE_URL=http://localhost:3003
      - VITE_PAYMENT_SERVICE_URL=http://localhost:3005
      - VITE_ATTENDANCE_SERVICE_URL=http://localhost:3004
    volumes:
      - ./apps/school-frontend:/app/apps/school-frontend
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/school-frontend/node_modules
      # Exclude built package dist folders
      - /app/packages/common-middleware/dist
      - /app/packages/common-utils/dist
      - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

  # Platform Frontend
  platform-frontend:
    build:
      context: .
      dockerfile: apps/platform-frontend/Dockerfile
    container_name: vidyalayaone-platform-frontend
    ports:
      - "8081:8081"
    depends_on:
      - api-gateway
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_AUTH_API_URL=http://localhost:3000/api/v1
      - VITE_SCHOOL_API_URL=http://localhost:3000/api/v1
      - VITE_PAYMENT_API_URL=http://localhost:3000/api/v1/payments
      - VITE_AUTH_SERVICE_URL=http://localhost:3001
      - VITE_SCHOOL_SERVICE_URL=http://localhost:3002
      - VITE_PROFILE_SERVICE_URL=http://localhost:3003
      - VITE_PAYMENT_SERVICE_URL=http://localhost:3005
      - VITE_ATTENDANCE_SERVICE_URL=http://localhost:3004
    volumes:
      - ./apps/platform-frontend:/app/apps/platform-frontend
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/platform-frontend/node_modules
      # Exclude built package dist folders
      - /app/packages/common-middleware/dist
      - /app/packages/common-utils/dist
      - /app/packages/logger/dist
    networks:
      - vidyalayaone-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  vidyalayaone-network:
    driver: bridge
